FROM node:17-alpine

ARG SERVER_URL
ENV SERVER_URL_VAR=$SERVER_URL

ARG GAME_TO_RUN
ENV GAME_TO_RUN_VAR=$GAME_TO_RUN

WORKDIR /app

COPY package*.json ./

RUN npm install 2>&1

COPY . ./

ENTRYPOINT npm start "$GAME_TO_RUN_VAR" "$SERVER_URL_VAR"