var ExcitebikeElement = module.exports = {

    //game element types
    NONE: ' ',
    FENCE: '■',

    ACCELERATOR: '>',
    INHIBITOR: '<',
    OBSTACLE: '|',
    LINE_CHANGER_UP: '▲',
    LINE_CHANGER_DOWN: '▼',

    //springboard elements types
    SPRINGBOARD_LEFT_UP: '╔',
    SPRINGBOARD_LEFT: '/',
    SPRINGBOARD_LEFT_DOWN: '╚',
    SPRINGBOARD_TOP: '═',
    SPRINGBOARD_RIGHT_UP: '╗',
    SPRINGBOARD_RIGHT: '\\',
    SPRINGBOARD_RIGHT_DOWN: '╝',

    //player bike    
    BIKE: 'B',
    BIKE_AT_ACCELERATOR: 'A',
    BIKE_AT_INHIBITOR: 'I',
    BIKE_AT_LINE_CHANGER_UP: 'U',
    BIKE_AT_LINE_CHANGER_DOWN: 'D',
    BIKE_AT_KILLED_BIKE: 'K',
    BIKE_AT_SPRINGBOARD_LEFT: 'L',
    BIKE_AT_SPRINGBOARD_LEFT_DOWN: 'M',
    BIKE_AT_SPRINGBOARD_RIGHT: 'R',
    BIKE_AT_SPRINGBOARD_RIGHT_DOWN: 'S',
    BIKE_IN_FLIGHT_FROM_SPRINGBOARD: 'F',

    BIKE_FALLEN: 'b',
    BIKE_FALLEN_AT_ACCELERATOR: 'a',
    BIKE_FALLEN_AT_INHIBITOR: 'i',
    BIKE_FALLEN_AT_LINE_CHANGER_UP: 'u',
    BIKE_FALLEN_AT_LINE_CHANGER_DOWN: 'd',
    BIKE_FALLEN_AT_FENCE: 'f',
    BIKE_FALLEN_AT_OBSTACLE: 'o',

    //enemy player bike    
    OTHER_BIKE: 'Ḃ',
    OTHER_BIKE_AT_ACCELERATOR: 'Ā',
    OTHER_BIKE_AT_INHIBITOR: 'Ī',
    OTHER_BIKE_AT_LINE_CHANGER_UP: 'Ū',
    OTHER_BIKE_AT_LINE_CHANGER_DOWN: 'Ď',
    OTHER_BIKE_AT_KILLED_BIKE: 'Ḱ',
    OTHER_BIKE_AT_SPRINGBOARD_LEFT: 'Ĺ',
    OTHER_BIKE_AT_SPRINGBOARD_LEFT_DOWN: 'Ṁ',
    OTHER_BIKE_AT_SPRINGBOARD_RIGHT: 'Ř',
    OTHER_BIKE_AT_SPRINGBOARD_RIGHT_DOWN: 'Ŝ',
    OTHER_BIKE_IN_FLIGHT_FROM_SPRINGBOARD: 'Ḟ',

    OTHER_BIKE_FALLEN: 'ḃ',
    OTHER_BIKE_FALLEN_AT_ACCELERATOR: 'ā',
    OTHER_BIKE_FALLEN_AT_INHIBITOR: 'ī',
    OTHER_BIKE_FALLEN_AT_LINE_CHANGER_UP: 'ū',
    OTHER_BIKE_FALLEN_AT_LINE_CHANGER_DOWN: 'ď',
    OTHER_BIKE_FALLEN_AT_FENCE: 'ḟ',
    OTHER_BIKE_FALLEN_AT_OBSTACLE: 'ō'
};
